---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: https://jellyfin.corp.aetherrootr.com
      description: video steaming
      server: local-docker
      container: jellyfin
      widget:
        type: jellyfin
        url: https://jellyfin.corp.aetherrootr.com
        key: 8c18ec538f734ee78bdc405353be1cae
        enableBlocks: true
        enableNowPlaying: true
   
  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.corp.aetherrootr.com
      description: tv manager
      server: local-docker
      container: sonarr
      widget:
        type: sonarr
        url: https://sonarr.corp.aetherrootr.com
        key: 081f19eaeb0b4140a41b5edd7546bf3d
        enableQueue: true

  - Radarr:
      icon: radarr.png
      href: https://radarr.corp.aetherrootr.com
      description: movies manager
      server: local-docker
      container: radarr
      widget:
        type: radarr
        url: https://radarr.corp.aetherrootr.com
        key: 6d6eadfa5d9344639d3c44ca755c5927
        enableQueue: true

  - Bazarr:
      icon: bazarr.png
      href: https://bazarr.corp.aetherrootr.com
      description: subtitles manager
      server: local-docker
      container: bazarr
      widget:
        type: bazarr
        url: https://bazarr.corp.aetherrootr.com
        key: fbec7507f749d3bafaf03999520b1e4a

  - qbittorrent:
      icon: qbittorrent.png
      href: http://go/torrent
      description: torrent downloader
      server: local-docker
      container: qbittorrent
      widget:
        type: qbittorrent
        url: http://192.168.8.137:8923

  - jackett:
      icon: jackett.svg
      href: http://go/jackett
      description: torrent source proxy
      server: local-docker
      container: jackett
      widget:
        type: jackett
        url: http://192.168.8.136:9117
        key: f4gaeehoartlr8m8ghn5stdxn1zt91wa

  - jellyseerr:
      icon: jellyseerr.svg
      href: http://192.168.8.136:5055
      description: video explorer
      server: local-docker
      container: jellyseerr
      widget:
        type: jellyseerr
        url: http://192.168.8.136:5055
        key: MTcwMjEzNjM1OTIwMzA3NjhmZjY5LTdjMDItNDM1Yi05NDIwLWUwYjc2NjZkMWU2MQ==

  - jproxy:
      icon: http://192.168.8.136:8117/assets/logo-128x128.24b61549.png
      href: http://192.168.8.136:8117/
      server: local-docker
      container: jproxy

- Tools:
  - it-tools:
      icon: https://it-tools.corp.aetherrootr.com/favicon.ico
      href: https://it-tools.corp.aetherrootr.com
      server: local-docker
      container: it-tools

  - cloud-clipboard:
      icon: https://clipboard.corp.aetherrootr.com/favicon.ico
      href: https://clipboard.corp.aetherrootr.com
      server: local-docker
      container: cloud-clipboard

  - jitsi-meet:
      icon: https://meet.corp.aetherrootr.com/static/pwa/icons/icon192.png
      href: https://meet.corp.aetherrootr.com/
  
  - kanboard:
      icon: https://tasks.corp.aetherrootr.com/assets/img/favicon.png
      href: https://tasks.corp.aetherrootr.com
      server: local-docker
      container: kanboard_kanboard_1

- Docs:
  - wikijs:
      icon: https://wiki.corp.aetherrootr.com/_assets/favicons/favicon-32x32.png
      href: https://wiki.corp.aetherrootr.com/
      server: local-docker
      container: wikijs_wiki_1

- Manager:
  - nginx-proxy-manager:
      icon: http://192.168.8.136:81/images/favicons/favicon.ico
      href: http://192.168.8.136:81
      server: local-docker
      container: nginx-proxy-manager_app_1

  - filebrowser:
      icon: https://files.corp.aetherrootr.com/filebrowser/static/img/logo.svg
      href: https://files.corp.aetherrootr.com/
      server: local-docker
      container: filebrowser_filebrowser_1
